services:
  - type: web
    name: i-healthconnect-backend
    env: node
    rootDir: backend
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Yosuwaniyigena%401@db.froyftducnbsxousotpe.supabase.co:5432/postgres
      - key: JWT_SECRET
        value: afibora_super_secret_jwt_key_2026_secure
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGINS
        value: https://i-health-connect-f7.vercel.app
