services:
  - type: web
    name: ihealthconnect-backend
    runtime: node
    repo: https://github.com/ChristianIshimwe7/I-HealthConnect
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://nmzmkkwhtgkspfvbdxgr.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_Tu-7n7V-kUpeVokv5w8rfQ_oJe9CDA7
      - key: JWT_SECRET
        value: afibora_super_secret_jwt_key_2026_secure
    plan: free
